export default {
	API_LOADING_START: 'API_LOADING_START',
	API_LOADING_END: 'API_LOADING_END',
	SET_DEVICE_HEIGHT: 'SET_DEVICE_HEIGHT',

	TMP_IMAGE_URI: 'TMP_IMAGE_URI',
	TMP_MULTIPLE_IMAGE: 'TMP/MULTIPLE',
	SET_DELIVERY_ISSUE_TITLE: 'SET_DELIVERY_ISSUE_TITLE',
	SET_DELIVERY_ISSUE_DESC: 'SET_DELIVERY_ISSUE_DESC',

	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',
	LOADING_AUTH: 'AUTH/LOADING',
	LOGIN_ERROR: 'AUTH/LOGIN_ERROR',

	SET_CONTACT: 'SET_CONTACT',
	CLEAR_CONTACT: 'CLEAR_CONTACT',
	LOADING_CONTACT: 'LOADING_CONTACT',

	SET_DELIVERY_LIST: 'SET_DELIVERY_LIST',
	LOADING_DELIVERY_LIST: 'LOADING_DELIVERY_LIST',
	CLEAR_DELIVERY_LIST: 'CLEAR_DELIVERY_LIST',

	SET_DELIVERY_HISTORY: 'SET/DELIVERY_HISTORY',
	SET_DELIVERY_HISTORY_ROUTE: 'SET/HISTORY_ROUTE',
	SET_DELIVERY_HISTORY_DETAIL: 'SET/HISTORY_ROUTE_DETAIL',

	SET_DELIVERY_CLIENT: 'SET_DELIVERY_CLIENT',
	VALIDATE_CLIENT: 'VALIDATE_CLIENT',
	LOADING_DELIVERY_CLIENT: 'LOADING_DELIVERY_CLIENT',
	LOADING_VALIDATE_CLIENT: 'LOADING_VALIDATE_CLIENT',
	VALIDATE_CLIENT_RESULT: 'VALIDATE_CLIENT_RESULT',

	SET_CLIENT_ITEMS: 'SET_CLIENT_ITEMS',
	SET_CLIENT_CARTS: 'SET_CLIENT_CARTS',
	SET_CLIENT_SO: 'SET_CLIENT_SO',
	LOADING_CLIENT_ITEMS: 'LOADING_CLIENT_ITEMS',
	LOADING_VALIDATE_CLIENT_ITEMS: 'LOADING_VALIDATE_CLIENT_ITEMS',
	STATUS_VALIDATE_CLIENT_ITEMS: 'STATUS_VALIDATE_CLIENT_ITEMS',

	LOADING_START_DELIVERY_CLIENT: 'LOADING_START_DELIVERY_CLIENT',
	UPDATE_DELIVERY_CLIENT_STATUS: 'UPDATE_DELIVERY_CLIENT_STATUS',

	LOADING_INPUT_KM: 'LOADING_INPUT_KM',
	STATUS_INPUT_KM: 'STATUS_INPUT_KM',

	TMP_NOTIF: 'TMP_NOTIF',

	STATUS_LOCATION: 'STATUS_LOCATION',
	SET_LATITUDE: 'SET_LATITUDE',
	SET_LONGITUDE: 'SET_LONGITUDE',

	LOADING_DELIVERY_PROCESS: 'LOADING_DELIVERY_PROCESS',
	SET_DELIVERY_PROCESS: 'SET_DELIVERY_PROCESS',
	ARRIVAL_LOADING: '@ARRIVE/LOADING',
	CLIENT_ARRIVAL_DATA: '@ARRIVE/DATA/SET',
	ARRIVAL_CONFIRMATION_SUCCESS: '@ARRIVE/SUCCESS',

	LOADING_COMPLAIN: '@COMPLAIN/LOADING',
	COMPLAIN_RESULT: '@COMPLAIN/RESULT',

	LOADING_DELIVERY_ISSUE: '@COMPLAIN/LOADING_DELIVERY',
	RESULT_DELIVERY_ISSUE: '@COMPLAIN/RESULT_DELIVERY',
};
