export default {
	API_LOADING_START: 'API_LOADING_START',
	API_LOADING_END: 'API_LOADING_END',
	SET_DEVICE_HEIGHT: 'SET_DEVICE_HEIGHT',

	TMP_IMAGE_URI: 'TMP_IMAGE_URI',

	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',

	SET_CONTACT: 'SET_CONTACT',
	CLEAR_CONTACT: 'CLEAR_CONTACT',
	LOADING_CONTACT: 'LOADING_CONTACT',
};
