export default {
	API_LOADING_START: 'API_LOADING_START',
	API_LOADING_END: 'API_LOADING_END',
	SET_DEVICE_HEIGHT: 'SET_DEVICE_HEIGHT',

	TMP_IMAGE_URI: 'TMP_IMAGE_URI',

	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',
	LOADING_AUTH: 'AUTH/LOADING',
	LOGIN_ERROR: 'AUTH/LOGIN_ERROR',

	SET_CONTACT: 'SET_CONTACT',
	CLEAR_CONTACT: 'CLEAR_CONTACT',
	LOADING_CONTACT: 'LOADING_CONTACT',

	SET_DELIVERY_LIST: 'SET_DELIVERY_LIST',
	LOADING_DELIVERY_LIST: 'LOADING_DELIVERY_LIST',
	CLEAR_DELIVERY_LIST: 'CLEAR_DELIVERY_LIST',

	TMP_NOTIF: 'TMP_NOTIF',
};
