export default {
	GET_CONTACT: '/',
	GET_PROFILE: (id: string) => (`users/${ id }/profile`),
	LOGIN: 'v1/auth/login',
	OTP_REQUEST: '/v1/otp/login-request',
	OTP_VERIFY: '/v1/otp/login-verify',
	RESET_PASSWORD: '/v1/auth/update-password',
	FORGOT_OTP_REQUEST: '/v1/otp/forgot-password-request',
	FORGOT_OTP_VERIFY: '/v1/otp/forgot-password-verify',
	DELIVERY_LIST: '/v1/delivery',
	DELIVERY_HISTORY_LIST: '/v1/delivery-history',
	GET_DELIVERY_PROCESS: '/v1/delivery-process',
	PUSH_NOTIF: '/v1/notifications/user-device',
	READ_NOTIF: (notifId: number) => (`v1/notifications/read/${ notifId }`),
	GET_NOTIFICATION: (link: string | undefined) => link ? link : (`/v1/notifications?order=id,desc&limit=10&offset=0`),
	DELIVERY_HISTORY_CLIENT_DETAIL: (deliveryId: string, clientId: string) => (`v1/delivery-history/${ deliveryId }/client/${ clientId }`),
	DELIVERY_HISTORY_ROUTE: (deliveryId: string) => (`v1/delivery-history/${ deliveryId }`),
	DELIVERY_CLIENT: (deliveryId: string) => (`v1/delivery-count-item/${ deliveryId }`),
	VALIDATE_CLIENT: (deliveryId: string, clientId: string) => (`v1/delivery-validate/${ deliveryId }/client/${ clientId }`),
	DELIVERY_CLIENT_ITEMS: (deliveryId: string, clientId: string) => (`v1/delivery/${ deliveryId }/client/${ clientId }`),
	DELIVERY_VALIDATE_ITEMS: (deliveryId: string, clientId: string) => (`v1/delivery-validate-item/${ deliveryId }/client/${ clientId }`),
	INPUT_KM: (deliveryId: string) => (`v1/delivery/${ deliveryId }/start`),
	INPUT_KM_FINISH: (deliveryId: string) => (`v1/delivery/${ deliveryId }/finish`),
	DELIVERY_PROCESS: (deliveryId: string) => (`v1/delivery-process/${ deliveryId }`),
	ADD_DELIVERY_ISSUE: (deliveryId: string, clientId: string) => (`v1/delivery-process/${ deliveryId }/problem-report/${ clientId }`),
	START_DELIVERY_CLIENT: (deliveryId: string, clientId: string) => (`v1/delivery-process/${ deliveryId }/client/${ clientId }`),
	JUST_ARRIVE: (deliveryId: string, clientId: string) => (`v1/delivery-arrival/${ deliveryId }/client/${ clientId }`),
	ARRIVAL_CONFIRMATION: (deliveryId: string, clientId: string) => (`v1/delivery-arrival/${ deliveryId }/client/${ clientId }/confirmation`),
	CLIENT_ARRIVAL: (deliveryId: string, clientId: string) => (`v1/delivery-arrival/${ deliveryId }/client/${ clientId }`),
	ADD_COMPLAINT: (deliveryId: string, clientId: string) => (`v1/delivery-complaint/${ deliveryId }/client/${ clientId }`),
	DELIVERY_COMPLAIN: (deliveryId: string, clientId: string, itemId: string) => (`v1/delivery-complaint/${ deliveryId }/client/${ clientId }/item/${ itemId }`)
};
