export default {
	USER_STATUS: {
		INACTIVE_USER: -1,
		UNVERIFIED_USER: 0,
		ACTIVE_USER: 1
	},
	DELIVERY_STATUS: {
		OPEN: 0,
		VALIDATE_CLIENT: 3,
		VALIDATE_ITEM: 4,
		SENT: 5,
		ARRIVED: 6,
		FINISH: 1
	}
};